'use client';

import React, { useState, useEffect, useMemo, ComponentType } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import * as Icons from 'lucide-react';
import Link from 'next/link';

interface LivePreviewProps {
  code: string;
  elementId: string;
}

class ErrorBoundary extends React.Component<{ children: React.ReactNode }, { hasError: boolean; error: Error | null }> {
  constructor(props: { children: React.ReactNode }) {
    super(props);
    this.state = { hasError: false, error: null };
  }

  static getDerivedStateFromError(error: Error) {
    return { hasError: true, error };
  }

  componentDidCatch(error: Error, errorInfo: React.ErrorInfo) {
    console.error('Live Preview Error:', error, errorInfo);
  }

  render() {
    if (this.state.hasError) {
      return (
        <div className="p-8 bg-red-500/10 border-2 border-dashed border-red-500/20 rounded-2xl text-center">
          <Icons.AlertTriangle className="w-12 h-12 text-red-500 mx-auto mb-4" />
          <h3 className="text-red-500 font-bold text-lg">Runtime Error</h3>
          <p className="text-red-400 text-sm mt-2 max-w-xs mx-auto font-mono">
            {this.state.error?.message}
          </p>
          <button 
            onClick={() => this.setState({ hasError: false, error: null })}
            className="mt-6 px-4 py-2 bg-red-500 text-white text-xs font-bold rounded-lg hover:bg-red-600 transition-colors"
          >
            Try Again
          </button>
        </div>
      );
    }

    return this.props.children;
  }
}

export default function LivePreview({ code, elementId }: LivePreviewProps) {
  const Component = useMemo(() => {
    if (!code) return null;

    try {
      // Create a scope for the component
      const scope = {
        React,
        useState,
        useEffect,
        motion,
        AnimatePresence,
        Icons,
        Link,
      };

      // Wrap the code to return the default export
      // The code generated by codegen.ts looks like:
      // 'use client';
      // import ...
      // export default function ComponentName() { ... }
      
      // We need to strip imports and exports for the function body
      let cleanCode = code
        .replace(/'use client';/g, '')
        .replace(/import\s+.*\s+from\s+['"].*['"];?/g, '')
        .replace(/export\s+default\s+function\s+\w+\s*\(/g, 'return function(')
        .replace(/export\s+default\s+function\s*\(/g, 'return function(');

      // Simple way to handle Icons as a global
      // The codegen uses (Icons as any).IconName
      
      const func = new Function(...Object.keys(scope), cleanCode);
      return func(...Object.values(scope));
    } catch (err) {
      console.error('Failed to create component:', err);
      return null;
    }
  }, [code]);

  if (!Component) {
    return (
      <div className="p-8 bg-zinc-900/50 border-2 border-dashed border-zinc-800 rounded-2xl text-center">
        <Icons.Loader2 className="w-12 h-12 text-zinc-700 mx-auto mb-4 animate-spin" />
        <h3 className="text-zinc-500 font-bold text-lg">Preparing Preview...</h3>
        <p className="text-zinc-600 text-sm mt-2">
          Click &quot;Save &amp; Run&quot; to update the live preview.
        </p>
      </div>
    );
  }

  return (
    <ErrorBoundary key={elementId + code.length}>
      <Component />
    </ErrorBoundary>
  );
}
